[package]
name = "whatssock-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = "1.23.2"
chrono = {version = "0.4.41", features = ["serde"]}
rmp-serde = "1.3.0"
serde = {version = "1.0.219", features = ["derive"]}
